### ISSUE TITLE
能问下博客是怎么自动同步的吗

### ISSUE THREAD

**Issue by roaming-debug** [yhyy135/yhyy135.github.io#1]
看了下这个项目的commit信息，貌似都是自动提交的，能问下是如何实现的吗？能否丢个教程link？

**Comment by chengtl5386** [comment]
您好，博客内容用visual studio本地编辑，然后下载GitHub桌面端自动push。发自我的华为手机-------- 原始邮件 --------发件人： driftingdream <notifications@github.com>日期： 2020年7月16日周四 21:33收件人： "yhyy135/yhyy135.github.io" <yhyy135.github.io@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [yhyy135/yhyy135.github.io] 能问下博客是怎么自动同步的吗 (#1)

看了下这个项目的commit信息，貌似都是自动提交的，能问下是如何实现的吗？能否丢个教程link？

**Comment by roaming-debug** [comment]
好的 谢谢
